######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 7 17:34:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
QT += network

# Input
HEADERS += PMaildServer.hpp PMaildCore.hpp
SOURCES += main.cpp PMaildServer.cpp
